.TH RM 1 rm
.SH NAME
rm - remove the specified files
.SH SYNOPSIS
.B rm
.IR FILE ...
.SH DESCRIPTION
Remove the inputted files if possible. Return 1
and print error information if an error occurs.
.SH AUTHOR
Written by Benjamin Brady.
.SH COPYRIGHT
Copyright \(co 2021 Benjamin Brady. License GPLv3+: GNU GPL version 3 or later
<https://gnu.org/licenses/gpl.html>. This is free software: you are free to
change and redistribute it. There is NO WARRANTY, to the extent permitted by
law.
.SH SEE ALSO
Jam Coreutils full documentation and source code is located at
<git://benjaminbrady.ie/jamutils.git/>.
