.TH TAIL 1 tail
.SH NAME
tail - output the last few lines (10 by default) of specified files
.SH SYNOPSIS
.B tail
.RB [ \-n
.IR lines ]
.IR FILE ...
.SH DESCRIPTION
Open all specified files and print the specified amount of lines from
the bottom. If no lines are specified then 10 are printed by default.
.SH AUTHOR
Written by Benjamin Brady.
.SH COPYRIGHT
Copyright \(co 2021 Benjamin Brady. License GPLv3+: GNU GPL version 3 or later
<https://gnu.org/licenses/gpl.html>. This is free software: you are free to
change and redistribute it. There is NO WARRANTY, to the extent permitted by
law.
.SH SEE ALSO
Jam Coreutils full documentation and source code is located at
<https://github.com/BenJaminBrady/jamutils/>.
