.TH WHOAMI 1 whoami
.SH NAME
whoami - print the current user
.SH SYNOPSIS
.B whoami
.SH DESCRIPTION
Print the current userid.

If an error is encountered then a detailed
error report is printed and 1 is returned.
.SH AUTHOR
Written by Benjamin Brady.
.SH COPYRIGHT
Copyright \(co 2021 Benjamin Brady. License GPLv3+: GNU GPL version 3 or later
<https://gnu.org/licenses/gpl.html>. This is free software: you are free to
change and redistribute it. There is NO WARRANTY, to the extent permitted by
law.
.SH SEE ALSO
Jam Coreutils full documentation and source code is located at
<git://benjaminbrady.ie/jamutils.git/>.
