.TH PATH 1 path
.SH NAME
path - print the absolute path to each inputted file
.SH SYNOPSIS
.B path
.IR FILE ...
.SH DESCRIPTION
Follow an inputted file to its actual location on disk and print
the absolute path (follow symlinks and the PATH variable as needed).
.SH AUTHOR
Written by Benjamin Brady.
.SH COPYRIGHT
Copyright \(co 2021 Benjamin Brady. License GPLv3+: GNU GPL version 3 or later
<https://gnu.org/licenses/gpl.html>. This is free software: you are free to
change and redistribute it. There is NO WARRANTY, to the extent permitted by
law.
.SH SEE ALSO
Jam Coreutils full documentation and source code is located at
<git://benjaminbrady.ie/jamutils.git/>.
