.TH PATH 1 path
.SH NAME
path - print the absolute path to each inputted file
.SH SYNOPSIS
.B path
.RB [ \-enq ]
.RB [ \-s
.IR stream ]
.IR FILE ...
.SH DESCRIPTION
Resolve each specified file to its actual location on disk and print the
absolute path, following symlinks and the PATH variable as needed.
.SH OPTIONS
.TP
.B \-e
End each path with a NUL. Ignore previous occurrences of \-n.
.TP
.B \-n
End each path with a newline (this is the default). Ignore previous occurrences
of \-e.
.TP
.B \-q
Do not print the specified file path before the absolute file path.
.TP
.BI \-s " stream
Write the specified file path to the given
.IR stream .
The streams are as follows:
.TP
\to
stdout
.TP
\te
stderr
.SH AUTHOR
Written by Benjamin Brady.
.SH COPYRIGHT
Copyright \(co 2021-2022 Benjamin Brady. License GPLv3+: GNU GPL version 3 or
later <https://gnu.org/licenses/gpl.html>. This is free software: you are free
to change and redistribute it. There is NO WARRANTY, to the extent permitted by
law.
.SH SEE ALSO
Jam Coreutils full documentation and source code is located at
<git://benjaminbrady.ie/jamutils.git/>.
