.TH PBD 1 "March 2022" Jamutils-JAMUTILS_VERSION
.SH NAME
pbd \- print the name of the current working directory.
.SH SYNOPSIS
.B pbd
.SH DESCRIPTION
Print the name of the current working directory (without the path prefix).
.SH AUTHOR
Written by Benjamin Brady.
.SH COPYRIGHT
Copyright \(co 2021\-2022 Benjamin Brady. License GPLv3+: GNU GPL version 3 or
later <https://gnu.org/licenses/gpl.html>. This is free software: you are free
to change and redistribute it. There is NO WARRANTY, to the extent permitted by
law.
.SH SEE ALSO
Jamutils full documentation and source code is located at
<git://benjaminbrady.ie/jamutils.git/>.
