.TH MIN 1 "March 2022" Jamutils-JAMUTILS_VERSION
.SH NAME
min \- print the minimum of the inputted set.
.SH SYNOPSIS
.B min
.I set
.SH DESCRIPTION
Print the minimum of the set.

A set consists of an arbitrary list of IEEE-754 floating point numbers.
.SH AUTHOR
Written by Benjamin Brady.
.SH COPYRIGHT
Copyright \(co 2021\-2022 Benjamin Brady. License GPLv3+: GNU GPL version 3 or
later <https://gnu.org/licenses/gpl.html>. This is free software: you are free
to change and redistribute it. There is NO WARRANTY, to the extent permitted by
law.
.SH SEE ALSO
Jamutils full documentation and source code is located at
<git://benjaminbrady.ie/jamutils.git/>.
