.TH SHUTDOWN 1 shutdown
.SH NAME
shutdown \- stop and power off a Linux system.
.SH SYNOPSIS
.B shutdown
.SH DESCRIPTION
Call the system shutdown function of the Linux kernel.

Linux must be the currently running kernel and the user must have sufficient
privileges in the form of having CAP_SYS_BOOT inside their user namespace for
.B shutdown
to function correctly.
.SH AUTHOR
Written by Benjamin Brady.
.SH COPYRIGHT
Copyright \(co 2021\-2022 Benjamin Brady. License GPLv3+: GNU GPL version 3 or
later <https://gnu.org/licenses/gpl.html>. This is free software: you are free
to change and redistribute it. There is NO WARRANTY, to the extent permitted by
law.
.SH SEE ALSO
Jam Coreutils full documentation and source code is located at
<git://benjaminbrady.ie/jamutils.git/>.
