.TH CAL 1 cal
.SH NAME
cal - print a calendar
.SH SYNOPSIS
.B cal
.RI [ MONTH ]
.RI [ YEAR ]
.SH DESCRIPTION
Print a calender of the specified month and year.
Take the current month and year if none are provided.

The accepted range for the month is 1-12 (January to February)
and the accepted range for the year is 0-99999.
.SH AUTHOR
Written by Benjamin Brady.
.SH COPYRIGHT
Copyright \(co 2021 Benjamin Brady. License GPLv3+: GNU GPL version 3 or later
<https://gnu.org/licenses/gpl.html>. This is free software: you are free to
change and redistribute it. There is NO WARRANTY, to the extent permitted by
law.
.SH SEE ALSO
Jam Coreutils full documentation and source code is located at
<https://github.com/BenJaminBrady/jamutils/>.
