.TH CLEANNAME 1 cleanname
.SH NAME
cleanname - optimise file paths to their most efficient form.
.SH SYNOPSIS
.B cleanname
.IR FILENAME ...
.SH DESCRIPTION
Interpret each argument as a filename and print the most
efficient path to the same file (assuming no links).
.SH AUTHOR
Written by Benjamin Brady.
.SH COPYRIGHT
Copyright \(co 2021 Benjamin Brady. License GPLv3+: GNU GPL version 3 or later
<https://gnu.org/licenses/gpl.html>. This is free software: you are free to
change and redistribute it. There is NO WARRANTY, to the extent permitted by
law.
.SH SEE ALSO
Jam Coreutils full documentation and source code is located at
<git://benjaminbrady.ie/jamutils.git/>.
