.TH CLEANNAME 1 "March 2022" Jamutils-JAMUTILS_VERSION
.SH NAME
cleanname \- optimise pathnames to their most efficient form.
.SH SYNOPSIS
.B cleanname
.RB [ \-d
.IR path ]
.IR pathname ...
.SH DESCRIPTION
Lexically process each specified
.I filename
and print the shortest equivalent string that would name the same file (not
including links to that file).

Interpret . and .. directories. Truncate multiple and trailing slashes.
.SH OPTIONS
.TP
.BI \-d " path
Prepend
.I path
to unrooted filenames before cleaning.
.SH AUTHOR
Written by Benjamin Brady.
.SH COPYRIGHT
Copyright \(co 2021\-2022 Benjamin Brady. License GPLv3+: GNU GPL version 3 or
later <https://gnu.org/licenses/gpl.html>. This is free software: you are free
to change and redistribute it. There is NO WARRANTY, to the extent permitted by
law.
.SH SEE ALSO
Jamutils full documentation and source code is located at
<git://benjaminbrady.ie/jamutils.git/>.
