.TH RETURN 1 return
.SH NAME
return = set the return value to the inputted integer (0 by default)
.SH SYNOPSIS
.B return
.RI [ INTEGER ]
.SH DESCRIPTION
Return the inputted integer. If none is entered then return 0.
.SH AUTHOR
Written by Benjamin Brady.
.SH COPYRIGHT
Copyright \(co 2021 Benjamin Brady. License GPLv3+: GNU GPL version 3 or later
<https://gnu.org/licenses/gpl.html>. This is free software: you are free to
change and redistribute it. There is NO WARRANTY, to the extent permitted by
law.
.SH SEE ALSO
Jam Coreutils full documentation and source code is located at
<git://benjaminbrady.ie/jamutils.git/>.
