.TH MULTIPLY 1 "March 2022" Jamutils-JAMUTILS_VERSION
.SH NAME
multiply \- print the product of the inputted set.
.SH SYNOPSIS
.B multiply
.RB [ \-f
.IR format ]
.I multiplicand
.SH DESCRIPTION
Take the product of the inputted
.I multiplicand
and print the result using the format "%.16G\\n" by default.

The
.I multiplicand
consists of an arbitrary list of IEEE-754 floating point numbers.

The product is computed in the order specified and no effort is made to
maintain associativity.
.SH OPTIONS
.TP
.BI \-f " format
Change the output format to
.IR format .
.SH AUTHOR
Written by Benjamin Brady.
.SH COPYRIGHT
Copyright \(co 2021\-2022 Benjamin Brady. License GPLv3+: GNU GPL version 3 or
later <https://gnu.org/licenses/gpl.html>. This is free software: you are free
to change and redistribute it. There is NO WARRANTY, to the extent permitted by
law.
.SH SEE ALSO
Jamutils full documentation and source code is located at
<git://benjaminbrady.ie/jamutils.git/>.
