.TH MULTIPLY 1 multiply
.SH NAME
multiply - multiply the inputted set
.SH SYNOPSIS
.B multiply
.RB MULTIPLICAND
.SH DESCRIPTION
Take all of the supplied arguments as 64-bit IEEE 754
floating point numbers and print the product.
.SH AUTHOR
Written by Benjamin Brady.
.SH COPYRIGHT
Copyright \(co 2021 Benjamin Brady. License GPLv3+: GNU GPL version 3 or later
<https://gnu.org/licenses/gpl.html>. This is free software: you are free to
change and redistribute it. There is NO WARRANTY, to the extent permitted by
law.
.SH SEE ALSO
Jam Coreutils full documentation and source code is located at
<https://github.com/BenJaminBrady/jamutils/>.
