.TH SEQ 1 seq
.SH NAME
seq - print values of a sequence of numbers
.SH SYNOPSIS
.B seq
.RI [ starting
.RI [ increment ]] ending
.SH DESCRIPTION
Print the elements of a sequence defined by starting at the starting point
and repeatedly changing by the increment until the ending point is surpassed.

If no starting point is given then it is assumed to be 0.
Additionally, if no increment is given then it is assumed to be 1.
.SH AUTHOR
Written by Benjamin Brady.
.SH COPYRIGHT
Copyright \(co 2021 Benjamin Brady. License GPLv3+: GNU GPL version 3 or later
<https://gnu.org/licenses/gpl.html>. This is free software: you are free to
change and redistribute it. There is NO WARRANTY, to the extent permitted by
law.
.SH SEE ALSO
Jam Coreutils full documentation and source code is located at
<https://github.com/BenJaminBrady/jamutils/>.
