.TH FACTORIAL 1 "March 2022" Jamutils-JAMUTILS_VERSION
.SH NAME
factorial \- print the factorial of each argument.
.SH SYNOPSIS
.B factorial
.RB [ \-f
.IR format ]
.IR int ...
.SH DESCRIPTION
Print the factorial of each
.IR int .
.SH OPTIONS
.TP
.BI \-f " format
Change the output format to
.IR format .
.SH AUTHOR
Written by Benjamin Brady.
.SH COPYRIGHT
Copyright \(co 2021\-2022 Benjamin Brady. License GPLv3+: GNU GPL version 3 or
later <https://gnu.org/licenses/gpl.html>. This is free software: you are free
to change and redistribute it. There is NO WARRANTY, to the extent permitted by
law.
.SH SEE ALSO
Jamutils full documentation and source code is located at
<git://benjaminbrady.ie/jamutils.git/>.
