.TH LOOP 1 loop
.SH NAME
loop - repeatedly print a string
.SH SYNOPSIS
.B loop
.RI [ STRING ]
.SH DESCRIPTION
Print the arguments in an infinite loop followed by a newline.
If no external arguments are supplied then the string "y" is used
followed by a newline as usual.
.SH AUTHOR
Written by Benjamin Brady.
.SH COPYRIGHT
Copyright \(co 2021 Benjamin Brady. License GPLv3+: GNU GPL version 3 or later
<https://gnu.org/licenses/gpl.html>. This is free software: you are free to
change and redistribute it. There is NO WARRANTY, to the extent permitted by
law.
.SH SEE ALSO
Jam Coreutils full documentation and source code is located at
<git://benjaminbrady.ie/jamutils.git/>.
