.TH MV 1 mv
.SH NAME
mv - move a file
.SH SYNOPSIS
.B mv
.R SOURCE
.B DESTINATION
.SH DESCRIPTION
Move a file from the source to the destination.
.SH AUTHOR
Written by Benjamin Brady.
.SH COPYRIGHT
Copyright \(co 2021 Benjamin Brady. License GPLv3+: GNU GPL version 3 or later
<https://gnu.org/licenses/gpl.html>. This is free software: you are free to
change and redistribute it. There is NO WARRANTY, to the extent permitted by
law.
.SH SEE ALSO
Jam Coreutils full documentation and source code is located at
<git://benjaminbrady.ie/jamutils.git/>.
