.TH BASENAME 1 basename
.SH NAME
basename - strip directory from filenames
.SH SYNOPSIS
.B basename
.IR FILENAME ...
.SH DESCRIPTION
Interpret each argument as a filename and print it without the
preceeding directory (provided there is a preceeding directory).
.SH AUTHOR
Written by Benjamin Brady.
.SH COPYRIGHT
Copyright \(co 2021 Benjamin Brady. License GPLv3+: GNU GPL version 3 or later
<https://gnu.org/licenses/gpl.html>. This is free software: you are free to
change and redistribute it. There is NO WARRANTY, to the extent permitted by
law.
.SH SEE ALSO
Jam Coreutils full documentation and source code is located at
<https://github.com/BenJaminBrady/jamutils/>.
