.TH UPTIME 1 uptime
.SH NAME
uptime - print the duration in which the system has been consecutively running
.SH SYNOPSIS
.B uptime
.SH DESCRIPTION
Print the amount of time the system has been running consecutively.

The display format is HH:MM:SS. The amount is days is
displayed before the time if it is greater than 0.
.SH AUTHOR
Written by Benjamin Brady.
.SH COPYRIGHT
Copyright \(co 2021 Benjamin Brady. License GPLv3+: GNU GPL version 3 or later
<https://gnu.org/licenses/gpl.html>. This is free software: you are free to
change and redistribute it. There is NO WARRANTY, to the extent permitted by
law.
.SH SEE ALSO
Jam Coreutils full documentation and source code is located at
<git://benjaminbrady.ie/jamutils.git/>.
