.TH UPTIME 1 "March 2022" Jamutils-JAMUTILS_VERSION
.SH NAME
uptime \- print the uptime of the system.
.SH SYNOPSIS
.B uptime
.SH DESCRIPTION
Print the elapsed time of PID1 in the format: "[[DD-]HH:]MM:SS".

This value describes the duration that the system has been consecutively
running for.
.SH EXTENDED DESCRIPTION
The elapsed time of PID1 is useful as the uptime of the entire system, but is
not generically the same timestamp that the kernel would measure.
.SH AUTHOR
Written by Benjamin Brady.
.SH COPYRIGHT
Copyright \(co 2021\-2022 Benjamin Brady. License GPLv3+: GNU GPL version 3 or
later <https://gnu.org/licenses/gpl.html>. This is free software: you are free
to change and redistribute it. There is NO WARRANTY, to the extent permitted by
law.
.SH SEE ALSO
Jamutils full documentation and source code is located at
<git://benjaminbrady.ie/jamutils.git/>.
