.TH CAT 1 cat
.SH NAME
cat - concatenate inputted files and print to stdout
.SH SYNOPSIS
.B cat
.IR FILES ...
.SH DESCRIPTION
Concatenate all inputted files in order and print the result to stdout.
.SH AUTHOR
Written by Benjamin Brady.
.SH COPYRIGHT
Copyright \(co 2021 Benjamin Brady. License GPLv3+: GNU GPL version 3 or later
<https://gnu.org/licenses/gpl.html>. This is free software: you are free to
change and redistribute it. There is NO WARRANTY, to the extent permitted by
law.
.SH SEE ALSO
Jam Coreutils full documentation and source code is located at
<https://github.com/BenJaminBrady/jamutils/>.
