.TH RANDOM 1 random
.SH NAME
random \- print the output of a pseudorandom number generator.
.SH SYNOPSIS
.B random
.RB [ \-h ]
.RI [ int ]
.SH OPTIONS
.TP
.B \-h
Print the codomain of the pseudorandom number generator.
.TP
.I int
Generate and print
.I int
numbers. The default is one.
.SH DESCRIPTION
Print the output of the POSIX stdlib.h pseudorandom number generator function
rand() with the current Unix Epoch time as the srand() seed.

The codomain of the pseudorandom number generator is [0, RAND_MAX], inclusive,
where RAND_MAX is a system specific constant defined in the stdlib.h system
header. It is guaranteed to be at least 32767.
.SH EXTENDED DESCRIPTION
Note that the rand() function is deterministic, hence if
.B random
is invoked multiple times before the system clock increments, then the outputs
will be identical.

Additionally, note that the rand() function is not (in general) a CSPRNG;
therefore, the output should never be used for cryptographic applications.
.SH AUTHOR
Written by Benjamin Brady.
.SH COPYRIGHT
Copyright \(co 2021\-2022 Benjamin Brady. License GPLv3+: GNU GPL version 3 or
later <https://gnu.org/licenses/gpl.html>. This is free software: you are free
to change and redistribute it. There is NO WARRANTY, to the extent permitted by
law.
.SH SEE ALSO
Jam Coreutils full documentation and source code is located at
<git://benjaminbrady.ie/jamutils.git/>.
