.TH RANDOM 1 random
.SH NAME
random - print the output of a pseudo random number generator
.SH SYNOPSIS
.B random
.RB [ \-c ]
.RI [ INTEGER ]
.SH OPTIONS
.TP
.B \-c
Print the codomain of the pseudo random number generator.
.TP
.B INTEGER
How many numbers to print (1 by default).
.SH DESCRIPTION
Print the output of the POSIX stdlib pseudo random number generator with the
srand seed given by the current Unix Epoch time.

The amount of random numbers printed is the inputted integer. If none is given
then the default is 1.

The range is [0, RAND_MAX] inclusive where RAND_MAX is a system specific
constant.
.SH AUTHOR
Written by Benjamin Brady.
.SH COPYRIGHT
Copyright \(co 2021 Benjamin Brady. License GPLv3+: GNU GPL version 3 or later
<https://gnu.org/licenses/gpl.html>. This is free software: you are free to
change and redistribute it. There is NO WARRANTY, to the extent permitted by
law.
.SH SEE ALSO
Jam Coreutils full documentation and source code is located at
<git://benjaminbrady.ie/jamutils.git/>.
