.TH RMDIR 1 rmdir
.SH NAME
rmdir - remove the specified directories
.SH SYNOPSIS
.B rm
.IR DIRECTORY ...
.SH DESCRIPTION
Remove the inputted directories if possible.

Return 1 if no directories are supplied.
If any error is encountered while deleting any file
then print detailed error information and return 2.
.SH AUTHOR
Written by Benjamin Brady.
.SH COPYRIGHT
Copyright \(co 2021 Benjamin Brady. License GPLv3+: GNU GPL version 3 or later
<https://gnu.org/licenses/gpl.html>. This is free software: you are free to
change and redistribute it. There is NO WARRANTY, to the extent permitted by
law.
.SH SEE ALSO
Jam Coreutils full documentation and source code is located at
<git://benjaminbrady.ie/jamutils.git/>.
