.TH RMDIR 1 "March 2022" Jamutils-JAMUTILS_VERSION
.SH NAME
rmdir \- remove the specified directories.
.SH SYNOPSIS
.B rmdir
.RB [ \-p ]
.IR directory ...
.SH DESCRIPTION
Attempt to remove the specified directories in the order given.
.SH OPTIONS
.TP
.B \-p
Remove all directories which appear in the pathname.
.SH EXIT STATUS
.TP
.B 0
Every specified
.I directory
was successfully removed.
.TP
.B 1
The invocation of
.B rmdir
was incorrect.
.TP
.B 2
An error occurred whilst removing a stipulated directory.
.SH AUTHOR
Written by Benjamin Brady.
.SH COPYRIGHT
Copyright \(co 2021\-2022 Benjamin Brady. License GPLv3+: GNU GPL version 3 or
later <https://gnu.org/licenses/gpl.html>. This is free software: you are free
to change and redistribute it. There is NO WARRANTY, to the extent permitted by
law.
.SH SEE ALSO
Jamutils full documentation and source code is located at
<git://benjaminbrady.ie/jamutils.git/>.
