.TH HEAD 1 "March 2022" Jamutils-JAMUTILS_VERSION
.SH NAME
head \- print the first few lines of files.
.SH SYNOPSIS
.B head
.RB [ \-n
.IR lines ]
.IR file ...
.SH DESCRIPTION
Copy the requested amount of
.I lines
from each
.I file
to standard output.

If the
.B \-n
flag was not specified, then print ten lines.
.SH OPTIONS
.TP
.BI \-n " lines"
Set the amount of
.I lines
to print.
.SH AUTHOR
Written by Benjamin Brady.
.SH COPYRIGHT
Copyright \(co 2021\-2022 Benjamin Brady. License GPLv3+: GNU GPL version 3 or
later <https://gnu.org/licenses/gpl.html>. This is free software: you are free
to change and redistribute it. There is NO WARRANTY, to the extent permitted by
law.
.SH SEE ALSO
Jamutils full documentation and source code is located at
<git://benjaminbrady.ie/jamutils.git/>.
