.TH DATE 1 date
.SH NAME
date - print the current time and date to stdout
.SH SYNOPSIS
.B date
.SH DESCRIPTION
Print the current time and date according to the system's local time in the
format DD Mon YYYY (Day) HH:MM:SS, where the hour is in 24-hour format.
.SH AUTHOR
Written by Benjamin Brady.
.SH COPYRIGHT
Copyright \(co 2021 Benjamin Brady. License GPLv3+: GNU GPL version 3 or later
<https://gnu.org/licenses/gpl.html>. This is free software: you are free to
change and redistribute it. There is NO WARRANTY, to the extent permitted by
law.
.SH SEE ALSO
Jam Coreutils full documentation and source code is located at
<git://benjaminbrady.ie/jamutils.git/>.
