.TH SYNC 1 sync
.SH NAME
sync - synchronise cached writes to file systems with persistent storage
.SH SYNOPSIS
.B sync
.SH DESCRIPTION
Update persistent storage with all information in memory which modifies file
systems.
.SH EXIT STATUS
The exit status is always 0.
.SH AUTHOR
Written by Benjamin Brady.
.SH COPYRIGHT
Copyright \(co 2021-2022 Benjamin Brady. License GPLv3+: GNU GPL version 3 or
later <https://gnu.org/licenses/gpl.html>. This is free software: you are free
to change and redistribute it. There is NO WARRANTY, to the extent permitted by
law.
.SH SEE ALSO
Jam Coreutils full documentation and source code is located at
<git://benjaminbrady.ie/jamutils.git/>.
