.TH ISPRIME 1 isprime
.SH NAME
isprime - determine whether or not each argument is a prime number
.SH SYNOPSIS
.B isprime
.IR INTEGER ...
.SH DESCRIPTION
Interpret each argument as an integer and
print whether or not it is a prime number.
.SH AUTHOR
Written by Benjamin Brady.
.SH COPYRIGHT
Copyright \(co 2021 Benjamin Brady. License GPLv3+: GNU GPL version 3 or later
<https://gnu.org/licenses/gpl.html>. This is free software: you are free to
change and redistribute it. There is NO WARRANTY, to the extent permitted by
law.
.SH SEE ALSO
Jam Coreutils full documentation and source code is located at
<https://github.com/BenJaminBrady/jamutils/>.
