.TH WC 1 "March 2022" Jamutils-JAMUTILS_VERSION
.SH NAME
wc \- print byte, line, and word counts of files.
.SH SYNOPSIS
.B wc
.RB [ \-c | \-m ]
.RB [ \-lw ]
.RI [ file ...]
.SH OPTIONS
.TP
.B \-c
Print the byte count of each
.IR file ,
replacing the character count.
.TP
.B \-l
Print the line count of each
.IR file .
.TP
.B \-m
Print the character count of each
.IR file ,
replacing the byte count.
.TP
.B \-w
Print the word count of each
.IR file .
.SH DESCRIPTION
Print various counts for each
.IR file .

If no flags are passed, then print all counts.

If more than one file is counted, then print the total for each attribute
count.
.SH EXIT STATUS
.TP
.B 0
The stipulated counts for each specified
.I file
were printed without error.
.TP
.B 1
The invocation of
.B wc
was invalid.
.TP
.B 2
An error occurred whilst writing any stipulated count for any file.
.SH AUTHOR
Written by Benjamin Brady.
.SH COPYRIGHT
Copyright \(co 2021\-2022 Benjamin Brady. License GPLv3+: GNU GPL version 3 or
later <https://gnu.org/licenses/gpl.html>. This is free software: you are free
to change and redistribute it. There is NO WARRANTY, to the extent permitted by
law.
.SH SEE ALSO
Jamutils full documentation and source code is located at
<git://benjaminbrady.ie/jamutils.git/>.
