.TH MKDIR 1 mkdir
.SH NAME
mkdir - make a directory at the specified location
.SH SYNOPSIS
.B mkdir
.IR DIRECTORY ...
.SH DESCRIPTION
Create directories at each specified location.
.SH AUTHOR
Written by Benjamin Brady.
.SH COPYRIGHT
Copyright \(co 2021 Benjamin Brady. License GPLv3+: GNU GPL version 3 or later
<https://gnu.org/licenses/gpl.html>. This is free software: you are free to
change and redistribute it. There is NO WARRANTY, to the extent permitted by
law.
.SH SEE ALSO
Jam Coreutils full documentation and source code is located at
<https://github.com/BenJaminBrady/jamutils/>.
