.TH PRIMES 1 "March 2022" Jamutils-JAMUTILS_VERSION
.SH NAME
primes \- print prime numbers in a range.
.SH SYNOPSIS
.B primes
.R starting
.RI [ ending ]
.SH DESCRIPTION
Print all of the prime numbers between the specified range, inclusive.

If only a starting point is given then print the lowest prime which is greater
than or equal to the starting point.
.SH AUTHOR
Written by Benjamin Brady.
.SH COPYRIGHT
Copyright \(co 2021\-2022 Benjamin Brady. License GPLv3+: GNU GPL version 3 or
later <https://gnu.org/licenses/gpl.html>. This is free software: you are free
to change and redistribute it. There is NO WARRANTY, to the extent permitted by
law.
.SH SEE ALSO
Jamutils full documentation and source code is located at
<git://benjaminbrady.ie/jamutils.git/>.
