.TH UNAME 1 "March 2022" Jamutils-JAMUTILS_VERSION
.SH NAME
uname \- print system information.
.SH SYNOPSIS
.B uname
.RI [ \-amnrsv ]
.SH OPTIONS
.TP
.B \-a
Print all information in the following order:
.TP
.B \-s
Print the name of the operating system
.TP
.B \-n
Print the hostname of this node on the network
.TP
.B \-r
Print the currently running release of the operating system
.TP
.B \-v
Print the currently running version of the operating system
.TP
.B \-m
Print the hardware type of the machine
.SH DESCRIPTION
Print system information as requested by the given flags.

If no flags are passed then the output will be equivalent to running:
.B
uname \-s
.R "."
.SH EXTENDED DESCRIPTION
Note that on GNU/Linux, the \-s, \-r, and \-v flags refer to the kernel's name,
release, and version respectively instead of the operating system.
.SH AUTHOR
Written by Benjamin Brady.
.SH COPYRIGHT
Copyright \(co 2021\-2022 Benjamin Brady. License GPLv3+: GNU GPL version 3 or
later <https://gnu.org/licenses/gpl.html>. This is free software: you are free
to change and redistribute it. There is NO WARRANTY, to the extent permitted by
law.
.SH SEE ALSO
Jamutils full documentation and source code is located at
<git://benjaminbrady.ie/jamutils.git/>.
