.TH UNAME 1 uname
.SH NAME
uname - print system information
.SH SYNOPSIS
.B uname
.SH DESCRIPTION
Print the system information. The information printed is:
operating system name, hostname (node name), operating system release,
operating system version, and the hardware identifier for the machine.
.SH AUTHOR
Written by Benjamin Brady.
.SH COPYRIGHT
Copyright \(co 2021 Benjamin Brady. License GPLv3+: GNU GPL version 3 or later
<https://gnu.org/licenses/gpl.html>. This is free software: you are free to
change and redistribute it. There is NO WARRANTY, to the extent permitted by
law.
.SH SEE ALSO
Jam Coreutils full documentation and source code is located at
<git://benjaminbrady.ie/jamutils.git/>.
